FROM ubuntu:24.04

RUN apt update && apt install -y \
    python3 python3-pip \
    cmake build-essential make gcc libffi-dev\
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements_linux.txt /requirements.txt

RUN pip install --break-system-packages -r /requirements.txt
RUN pip install --break-system-packages requests

COPY ./hermes_cad /hermes_cad
COPY ./hermes_ecossistema /hermes_ecossistema
COPY ./staticfiles /staticfiles
COPY ./manage.py /manage.py

RUN python3 manage.py collectstatic --noinput

EXPOSE 8002
EXPOSE 8001
EXPOSE 80
EXPOSE 50051

# Para Rodar daphne / WS
# CMD ["daphne", "hermes_ecossistema.asgi:application", "-b", "0.0.0.0", "-p", "80"]

# Para Rodar uvicorn / django
CMD ["uvicorn", "hermes_ecossistema.asgi:application", "--host", "0.0.0.0", "--port", "80"]
