syntax = "proto3";
package hermes;

service HermesService {
    // RPC 1: Para o fluxo de áudio do CAD para o Hermes
    // Cliente envia um fluxo continuo de áudio, servidor retorna uma única resposta de confirmação.
    rpc SendAudio (stream AudioStream) returns (AudioResponse);

    // RPC 2: Para o fluxo de áudio e texto entre Hermes e Transcription
    // O cliente envia um stream de áudio e o servidor retorna um stream de texto.
    rpc ProcessAndTranscribe (stream AudioStream) returns (stream TranscriptionResponse);
}


message AudioStream {
  string id = 1;
  bytes audioData = 2;
}

//Confirmação simples
message AudioResponse {
  string status = 1;
  string message = 2;
}

message TranscriptionResponse {
    string text_chunk = 1;
    bool end_of_stream = 2; // Sinalizar o fim da transcrição
}