services:
  staging:
    image: alpine:3.14
    volumes:
      - ${LOCAL_SQL_DB_PATH}:/app/sqlite_data
      - ./src/init.sql:/init.sql
    command: >
      sh -c "
        apk add --no-cache sqlite &&
        sqlite3 $SQLITE_DB_PATH < /init.sql &&
        echo 'SQLite inicializado. '
      "
    env_file: docker/common.env
  hermes-api:
    depends_on:
      - staging
    build:
      dockerfile: docker/Dockerfile.hermes
    ports:
      - "${HERMES_PORT}:${HERMES_PORT}"
    volumes:
      - ${LOCAL_SQL_DB_PATH}:/app/sqlite_data
      - ./logs/:/logs
      - hf_cache_vol:/tmp/hf_cache_dir
      - ./src/hermes:/src
    env_file: docker/common.env
  hermes-ner:
    depends_on:
      - staging
    build:
      dockerfile: docker/Dockerfile.ner_nvidia

    #ports:
    #  - "XXXX:XXXX"
    volumes:
      - ${LOCAL_SQL_DB_PATH}:/app/sqlite_data
      - ./logs/:/logs
      - hf_cache_vol:/tmp/hf_cache_dir
      - ./src/ner:/src
      - /tmp:/tmp
      - ./config.json:/config.json
    env_file: docker/nvidia.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host  # Shared memory performance
    runtime: nvidia  # Required for GPU access
    ulimits:
      memlock: -1  # Unlimited locked memory
      stack: 67108864  # 64MB stack size
  hermes-asr:
    depends_on:
      - staging
    build:
      dockerfile: docker/Dockerfile.asr_nvidia

    #ports:
    #  - "XXXX:XXXX"
    volumes:
      - ${LOCAL_SQL_DB_PATH}:/app/sqlite_data
      - ./logs/:/logs
      - hf_cache_vol:/tmp/hf_cache_dir
      - ./src/asr:/src
      - /tmp:/tmp
      - ./config.json:/config.json
    env_file: docker/nvidia.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host  # Shared memory performance
    runtime: nvidia  # Required for GPU access
    ulimits:
      memlock: -1  # Unlimited locked memory
      stack: 67108864  # 64MB stack size
  hermes-interpretation:
    build:
      dockerfile: docker/Dockerfile.interpretation_nvidia
    #ports:
    #  - "XXXX:XXXX"
    volumes:
      - ${LOCAL_SQL_DB_PATH}:/app/sqlite_data
      - ./logs/:/logs
      - hf_cache_vol:/tmp/hf_cache_dir
      - ./src/interpretation:/src
      - /tmp:/tmp
      - ./datasets:/datasets
      - ./config.json:/config.json
    env_file: docker/nvidia.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host  # Shared memory performance
    runtime: nvidia  # Required for GPU access
    ulimits:
      memlock: -1  # Unlimited locked memory
      stack: 67108864  # 64MB stack size
volumes:
  hf_cache_vol: