FROM ubuntu:24.04

RUN apt update && apt install -y \
    python3 python3-pip \
    cmake build-essential make gcc sqlite3 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --break-system-packages "fastapi[standard]"
RUN pip install --break-system-packages scipy numpy python-multipart
RUN pip install --break-system-packages librosa
RUN pip install --break-system-packages soundfile
RUN pip freeze > /requirements2.txt
#RUN pip install -r /requirements.txt --break-system-packages

COPY ./src/hermes /src
COPY ./src/init.sql /init.sql

#set open port 8000
EXPOSE 8001

CMD ["fastapi", "dev", "--host", "0.0.0.0", "--port", "8001", "/src/start.py"]