FROM ubuntu:24.04

RUN apt update && apt install -y \
    ffmpeg python3 python3-pip \
    cmake build-essential make gcc sqlite3 \
    build-essential libboost-system-dev libboost-thread-dev \
    libboost-program-options-dev libboost-test-dev libboost-filesystem-dev \
    && rm -rf /var/lib/apt/lists/*

#RUN pip install --break-system-packages transformers
#RUN pip install --break-system-packages -U datasets
#RUN pip install --break-system-packages torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install google-cloud-speech librosa numpy soundfile pydub tritonclient[http] --break-system-packages
RUN pip cache purge
RUN pip freeze > /requirements.txt

COPY ./src/interpretation /src

#set open port 8001
#EXPOSE 8001

CMD ["python3", "-u", "/src/start.py"]