FROM ubuntu:24.04

RUN apt update && apt install -y \
    python3 python3-pip \
    cmake build-essential make gcc sqlite3 libnuma-dev \
    build-essential libboost-system-dev libboost-thread-dev \
    libboost-program-options-dev libboost-test-dev libboost-filesystem-dev \
    && rm -rf /var/lib/apt/lists/*
#RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128 --break-system-packages
RUN pip install --break-system-packages pydantic uv
RUN uv pip install --break-system-packages pandas scikit-learn --system
RUN apt update && apt install -y \
    libopenblas-dev libblas-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --break-system-packages torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install --break-system-packages --upgrade huggingface_hub datasets transformers
RUN pip install --break-system-packages --upgrade openai google-genai

RUN pip cache purge
RUN pip freeze > /requirements2.txt

COPY ./datasets/ /datasets
COPY ./src/init.sql /init.sql
COPY ./src/interpretation /src
#COPY ../../config.json /app/config.json

#set open port 8001
#EXPOSE 8001

CMD ["python3", "-u", "/src/start.py"]